- name: "macOS Development Environment Setup"
  hosts: localhost
  connection: local
  vars:
    brew_cask_packages:
      - dbeaver-community
      - google-chrome
      - spotify
      - visual-studio-code
      - warp
      - whatsapp
    brew_packages:
      - docker
      - nvm
      
  pre_tasks:
    - name: Check if Homebrew is installed
      stat:
        path: /usr/local/bin/brew
      register: homebrew_check

    - name: Installing Homebrew
      shell: NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      when:
        - not homebrew_check.stat.exists

  tasks:
    - name: Updating Homebrew
      homebrew:
        update_homebrew: true
      when: homebrew_check.stat.exists

    - name: Upgrading Homebrew Packages
      homebrew:
        upgrade_all: "{{ upgrade_homebrew_packages }}"
      register: result
      until: result is successful
      when: homebrew_check.stat.exists

    - name: Installing Homebrew Cask Packages
      homebrew_cask:
        name: "{{ brew_cask_packages }}"
        state: present
      register: result
      until: result is successful
      when: homebrew_check.stat.exists

    - name: Installing Homebrew Packages
      homebrew:
        name: "{{ brew_packages }}"
        state: present
      register: result
      until: result is successful
      when: homebrew_check.stat.exists
    
    post_tasks
      - name: Check if folder nvm exists
        state:
          path: ~/.nvm
        register: nvm_check

      - name: Create nvm folder
        ansible.builtin.file:
          path: ~/.nvm
          state: directory
        when: 
          - not nvm_check.state.exists
