- name: "MacOS Dev Setup"
  hosts: localhost
  connection: local

  pre_tasks:
    - name: Check if Homebrew is installed
      stat:
        path: /usr/local/bin/brew
      register: homebrew_check

    - name: Installing Homebrew
      shell: NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      when:
        - not homebrew_check.stat.exists
