- name: Raspberry Pi Main Ansible Playbook
  hosts: localhost
  connection: local
  gather_facts: true
  become: yes

  pre_tasks:
    - name: apt-get dist-upgrade
      apt:
        upgrade: dist
    - name: apt-get update
      apt:
        update_cache: yes
    - name: apt-get upgrade
      apt:
        name: "*"
        state: latest

  tasks:
    - name: Install Node v20.x and PM2
      import_tasks: tasks/node.yml
    - name: Install Docker
      import_tasks: tasks/docker.yml

  post_tasks:
    - name: apt-get autoclean and autoremove
      apt:
        autoclean: yes
        autoremove: yes
