- name: Add Docker repository key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/raspbian/gpg
    state: present
- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: deb [arch=armhf] https://download.docker.com/linux/raspbian bookworm stable
    state: present
- name: Install Docker
  ansible.builtin.apt:
    name:
      - ca-certificates
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: true
