- name: Install Nginx
  apt:
    name: nginx
    state: present
- name: Start Nginx service
  service:
    name: nginx
    state: started
    enabled: true
- name: Create group 'nginx'
  ansible.builtin.group:
    name: "nginx"
    local: yes
  with_items:
    - nginx
    - svc_web_server
- name: Add the user 'svc_web_server' with a bash shell, appending the group 'sudo' to the user's groups
  ansible.builtin.user:
    name: svc_web_server
    shell: /bin/bash
    groups: sudo
    append: yes
