- name: Add NodeSource v22 repo
  ansible.builtin.shell: curl -fsSL https://deb.nodesource.com/setup_22.x | sudo bash -
  state: present
- name: Install Node.js
  ansible.builtin.apt:
    name: nodejs
    update_cache: true
- name: Install PM2
  community.general.npm:
    name: pm2
    global: true
