- name: macOS Development Environment Setup
  hosts: localhost
  connection: local
  gather_facts: true
  vars:
    brew_cask_packages:
      - dbeaver-community
      - docker
      - google-chrome
      - logi-options-plus
      - spotify
      - visual-studio-code
      - vlc
      - vnc-viewer
      - warp
      - whatsapp
    brew_packages:
      - gh
      - m-cli
      - nvm
      - pnpm
      - yarn
    upgrade_homebrew_packages: true

  pre_tasks:
    - name: Check if Homebrew is installed (Intel Based Macs)
      stat:
        path: /usr/local/bin/brew
      register: homebrew_check
      when: ansible_architecture == "x86_64"

    - name: Check if Homebrew is installed (Apple-Silicon Based Macs)
      stat:
        path: /usr/local/bin/brew
      register: homebrew_check
      when: ansible_architecture == "arm64"

    - name: Installing Homebrew
      shell: NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      when:
        - not homebrew_check.stat.exists

  tasks:
    - name: Updating Homebrew
      homebrew:
        update_homebrew: true
      when: homebrew_check.stat.exists

    - name: Upgrading Homebrew Packages
      homebrew:
        upgrade_all: "{{ upgrade_homebrew_packages }}"
      register: result
      until: result is successful
      when: homebrew_check.stat.exists

    - name: Installing Homebrew Cask Packages
      homebrew_cask:
        name: "{{ brew_cask_packages }}"
        state: present
      register: result
      until: result is successful
      when:
        - homebrew_check.stat.exists

    - name: Installing Homebrew Packages
      homebrew:
        name: "{{ brew_packages }}"
        state: present
      register: result
      until: result is successful
      when:
        - homebrew_check.stat.exists

    - name: Configure nvm and install Node LTS
      import_tasks: tasks/configure-nvm-and-install-node-lts.yml

    - name: Setup git config
      import_tasks: tasks/setup-git-config.yml

    - name: Setup dock
      import_tasks: tasks/setup-dock.yml
